### ISSUE TITLE
Help me with problem of debugging in Pio, plsssss

### ISSUE THREAD

**Issue by ghost** [jdolinay/avr_debug#52]
Hi admin, I'm new in using debug with arduino code. Because of my immaturity, allow me to ask about my problem:
I want to debug with Pio on VS code platform and I followed your instructions and fully loaded the latest library but I keep getting errors.
Let me know if I missed something or help me to fix it. Thanks
This is my code :
` #include <Arduino.h>
  #ifdef DEBUG_AVR
  #include <avr8-stub.h>
  #include <app_api.h>
  #endif
  #include <RFID.h>
  #include <SPI.h>
  #include <LiquidCrystal_I2C.h>
  #include <Wire.h>
  RFID rfid (10, 9);
  LiquidCrystal_I2C lcd(0x27, 20, 4);
  int nutbam1  = 6;
  int nutbam2  = 5;
  int nutbam3  = 4;
  int biendemactive   = 0;
  int biendemapp      = 0;
  int biendemmenu     = 0;
  int biendemcontrol  = 0;
  int biendemcontent  = 0;
  int biendemexit     = 0;
  int biendemquatrinh = 0;
  int serNum0;
  int serNum1;
  int serNum2;
  int serNum3;
  int serNum4;
  //ON-OFF
  void on() {
    lcd.clear();
    lcd.backlight();
    lcd.setCursor(6, 0);
    lcd.print("XIN CHAO");
    lcd.setCursor(3, 2);
    lcd.print(" CARD");
    lcd.setCursor(12, 2);
    lcd.print(" MENU");
  }
  // MÀN HÌNH CHÍNH
  void mainscreen() {
    if (biendemapp % 2 == 1) {
      lcd.clear();
      lcd.setCursor(6, 0);
      lcd.print("XIN CHAO");
      lcd.setCursor(3, 2);
      lcd.print(">CARD");
      lcd.setCursor(12, 2);
      lcd.print(" MENU");
    }
    if (biendemapp % 2 == 0) {
      lcd.clear();
      lcd.setCursor(6, 0);
      lcd.print("XIN CHAO");
      lcd.setCursor(3, 2);
      lcd.print(" CARD");
      lcd.setCursor(12, 2);
      lcd.print(">MENU");
    }
  }
  // MÀN HÌNH ỨNG DỤNG
  void applicant() {
    if (biendemapp % 2 == 1) {
      lcd.clear();
      lcd.print("THE CUA BAN");
    }
    if (biendemapp % 2 == 0) {
      lcd.clear();
      lcd.print(">MENU 1");
      lcd.setCursor(0, 1);
      lcd.print(" MENU 2");
      lcd.setCursor(0, 2);
      lcd.print(" MENU 3");
      lcd.setCursor(0, 3);
      lcd.print(" BACK");
    }
  }
  // MÀN HÌNH ĐIỀU KHIỂN MENU
  void controlmenu() {
    if (biendemcontrol % 4 == 0) {
      lcd.clear();
      lcd.print(">MENU 1");
      lcd.setCursor(0, 1);
      lcd.print(" MENU 2");
      lcd.setCursor(0, 2);
      lcd.print(" MENU 3");
      lcd.setCursor(0, 3);
      lcd.print(" BACK");
    }
    if (biendemcontrol % 4 == 1) {
      lcd.clear();
      lcd.print(" MENU 1");
      lcd.setCursor(0, 1);
      lcd.print(">MENU 2");
      lcd.setCursor(0, 2);
      lcd.print(" MENU 3");
      lcd.setCursor(0, 3);
      lcd.print(" BACK");
    }
    if (biendemcontrol % 4 == 2) {
      lcd.clear();
      lcd.print(" MENU 1");
      lcd.setCursor(0, 1);
      lcd.print(" MENU 2");
      lcd.setCursor(0, 2);
      lcd.print(">MENU 3");
      lcd.setCursor(0, 3);
      lcd.print(" BACK");
    }
    if (biendemcontrol % 4 == 3) {
      lcd.clear();
      lcd.print(" MENU 1");
      lcd.setCursor(0, 1);
      lcd.print(" MENU 2");
      lcd.setCursor(0, 2);
      lcd.print(" MENU 3");
      lcd.setCursor(0, 3);
      lcd.print(">BACK");
    }
  }
  // MÀN HÌNH NỘI DUNG
  void content() {
   if (biendemcontrol % 4 == 0) {
      lcd.clear();
      lcd.setCursor(3, 1);
      lcd.print("NOI DUNG MENU 1");
      lcd.setCursor(0, 3);
      lcd.print(">BACK");
    }
    if (biendemcontrol % 4 == 1) {
      lcd.clear();
      lcd.setCursor(3, 1);
      lcd.print("NOI DUNG MENU 2");
      lcd.setCursor(0, 3);
      lcd.print(">BACK");
    }
    if (biendemcontrol % 4 == 2) {
      lcd.clear();
      lcd.setCursor(3, 1);
      lcd.print("NOI DUNG MENU 3");
      lcd.setCursor(0, 3);
      lcd.print(">BACK");
    }
    if (biendemcontrol % 4 == 3) { 
      lcd.clear();
      mainscreen();
      biendemcontrol=0;
      biendemmenu=0;
      biendemquatrinh=0;
    }
  }
  //THOÁT NỘI DUNG
  void exitcontent() {
    lcd.clear();
    controlmenu();
    biendemquatrinh=1;
    biendemmenu=1; 
  }
  void setup() {
    debug_init();
    Serial.begin(9600);
    lcd.begin();
    lcd.noBacklight();
    SPI.begin();
    pinMode(nutbam1, INPUT_PULLUP);
    pinMode(nutbam2, INPUT_PULLUP);
    pinMode(nutbam3, INPUT_PULLUP);
  }
  void loop() {
    int(trangthai1) = digitalRead(nutbam1);
    int(trangthai2) = digitalRead(nutbam2);
    int(trangthai3) = digitalRead(nutbam3);
    Serial.println();
    Serial.print(biendemquatrinh);
    Serial.print(biendemapp);
    Serial.print(biendemmenu);
    Serial.print(biendemcontrol);
    Serial.print(biendemcontent);
    //TẮT MỞ MENU
    if (trangthai1 == 0) {
      biendemactive++;
      if (biendemactive % 2 == 1) {
        on();
      }
      if (biendemactive % 2 == 0) {
        lcd.clear();
        lcd.noBacklight();
        if (biendemapp != 0)
          biendemapp=0;
        if (biendemmenu != 0)
          biendemmenu=0;
        if (biendemcontrol != 0)
          biendemcontrol=0;
        if (biendemcontent != 0)
          biendemcontent=0;
        if (biendemquatrinh != 0)
          biendemquatrinh=0;
      }
      delay(300);
    }
    //SETUP QUÁ TRÌNH
    if (biendemactive % 2 == 1) {  
      if (biendemapp > 0) {
        if (trangthai3 == 0) {
          biendemquatrinh++;
          delay(300);
        }
      }
    }
    //MÀN HÌNH CHÍNH
    if (biendemactive % 2 == 1) {  
      if (trangthai2 == 0) {
        if (biendemquatrinh == 0) {
          biendemapp++;
          mainscreen();
        }
        delay(200);
      }
    }
    //CHỌN ỨNG DỤNG
    if (biendemactive % 2 == 1) {
      if (biendemapp > 0) {
        if (trangthai3 == 0) {
          if (biendemquatrinh == 1) {
            biendemcontent=0;
            biendemmenu++;
            if (biendemmenu >= 1) {
              applicant();
            }
          }
          delay(200);
        }
      }
    }
    //ĐIỀU KHIỂN MENU
    if (biendemactive % 2 == 1) {
      if (biendemmenu > 0) {
        if (biendemquatrinh == 1) {
          if (trangthai2 == 0) {
            biendemcontrol++;
            controlmenu();
            delay(200);  
          }
        }
      }
    }
    //CHỌN NỘI DUNG
    if (biendemactive % 2 == 1) {
      if (trangthai3 == 0) {
        if (biendemquatrinh >= 2) {
          biendemcontent++;
          if (biendemcontent > 0) {
            if (biendemcontent %2 == 1) {
              content();
            }
            if (biendemcontent %2 == 0) {
              exitcontent();
            }
          }
        } 
        delay(200);
      }
    }
  }
`
And this is my error :+1: 
`Executing task: C:\Users\LENOVO\.platformio\penv\Scripts\platformio.exe debug 

Processing uno (platform: atmelavr; board: uno; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
Removing unused dependencies...
Error: Traceback (most recent call last):
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\cli.py", line 70, in invoke
    return super().invoke(ctx)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\debug\cli.py", line 85, in cli
    return helpers.predebug_project(
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\debug\helpers.py", line 102, in predebug_project
    ctx.invoke(
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\run\cli.py", line 145, in cli
    process_env(
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\run\cli.py", line 198, in process_env
    result["succeeded"] = EnvironmentProcessor(
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\run\processor.py", line 81, in process
    install_project_env_dependencies(
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\package\commands\install.py", line 132, in install_project_env_dependencies
    _install_project_env_libraries(project_env, options),
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\package\commands\install.py", line 204, in _install_project_env_libraries
    _uninstall_project_unused_libdeps(project_env, options)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\package\commands\install.py", line 280, in _uninstall_project_unused_libdeps
    lm.uninstall(spec)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\package\manager\_uninstall.py", line 29, in uninstall
    return self._uninstall(spec, skip_dependencies)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\package\manager\_uninstall.py", line 34, in _uninstall
    pkg = self.get_package(spec)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\package\manager\base.py", line 263, in get_package
    spec = self.ensure_spec(spec)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\package\manager\base.py", line 133, in ensure_spec
    return spec if isinstance(spec, PackageSpec) else PackageSpec(spec)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 183, in __init__
    self._parse(self.raw)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 290, in _parse
    raw = parser(raw)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 315, in _parse_requirements
    self.requirements = tokens[1].strip()
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\platformio\package\meta.py", line 230, in requirements
    else semantic_version.SimpleSpec(str(value))
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\semantic_version\base.py", line 647, in __init__
    self.clause = self._parse_to_clause(expression)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\semantic_version\base.py", line 1043, in _parse_to_clause
    return cls.Parser.parse(expression)
  File "C:\Users\LENOVO\.platformio\penv\lib\site-packages\semantic_version\base.py", line 1063, in parse
    raise ValueError("Invalid simple block %r" % block)
ValueError: Invalid simple block '`'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================
![2023-06-28 (1)](https://github.com/jdolinay/avr_debug/assets/137923374/725890f5-faad-41c2-a6ab-c427e6272f20)
![2023-06-28 (2)](https://github.com/jdolinay/avr_debug/assets/137923374/7b09f96e-d34f-405f-a440-a40e74adaeee)
`

**Comment by jdolinay** [comment]
Hi, This looks like some basic problem with PIO configuration. The instructions in my docs may be out of date. Please try the official PIO instructions here https://docs.platformio.org/en/stable/plus/debug-tools/avr-stub.html. If that does not help you can try to ask in PIO forum.

**Comment by ghost** [comment]
I get the problem is in the command line lib_deps =
    jdolinay/avr-debugger @^1.5 because when I remove this command my OUTPUT doesn't crash, but I still can't debug
![2023-06-28 (7)](https://github.com/jdolinay/avr_debug/assets/137923374/c9ea5d0e-0b97-4b1b-a5d1-9766836aa0bc)
![2023-06-28 (8)](https://github.com/jdolinay/avr_debug/assets/137923374/5862535a-7274-49a1-ba98-baac2e583cfc)
